# Generated by Django 5.2 on 2025-05-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exame',
            options={'ordering': ['data_cadastro']},
        ),
    ]
