# Generated by Django 5.2 on 2025-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exames', '0002_alter_exame_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=1, verbose_name='Gênero'),
        ),
    ]
