# Generated by Django 5.2 on 2025-05-19 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=1, verbose_name='Gênero')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter exatamente 11 dígitos numéricos')], verbose_name='CPF')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Cadastro')),
                ('inicio_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Início de Atendimento')),
                ('sala_atendimento', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ExameFinalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('data_cadastro', models.DateTimeField()),
                ('inicio_atendimento', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Atendido'), ('C', 'Cancelado')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Exame Concluído',
                'verbose_name_plural': 'Exames Concluídos',
                'ordering': ['-data_finalizacao'],
            },
        ),
    ]
