# Generated by Django 5.2 on 2025-05-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examefinalizado',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Completo'),
        ),
    ]
